services:
  redis:
    image: redis:7-alpine
    container_name: aura_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: aura_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: aura_worker
    command: celery -A ecommerce worker --loglevel=info
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
