# Generated by Django 6.0.6 on 2026-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loyaltypoints_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_rate', models.IntegerField(default=1, help_text='Points earned per ₹100 spent.')),
                ('redemption_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Cash value (₹) per 1 point.', max_digits=5)),
                ('daily_points_min', models.IntegerField(default=50, help_text='Minimum daily claim login points.')),
                ('daily_points_max', models.IntegerField(default=150, help_text='Maximum daily claim login points.')),
                ('terms_and_conditions', models.TextField(default='1. Earn 1 point for every ₹100 spent on paid orders.\n2. Redeem points at checkout (1 point = ₹1 discount).\n3. Claim free points daily.', help_text='Custom terms text displayed on the loyalty page.')),
            ],
            options={
                'verbose_name': 'Loyalty Settings',
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
    ]
